imports:
  - { resource: config.yml }
  - { resource: service.sae.yml }
  - { resource: parameters.sae.xml }

parameters:
    kernel:
        cache_dir: 'saekv://var/cache/%kernel.environment%'
        logs_dir: 'saekv://var/logs/$kernel.environment%'

twig:
    cache: '%kernel.cache_dir%/twig'

framework:
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.memcache
    annotations:
        cache: doctrine.cache.memcache

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%sae_database_host%"
        port:     "%sae_database_port%"
        name:     "%sae_database_name%"
        user:     "%sae_database_user%"
        password: "%sae_database_password%"
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.cache.memcache
        query_cache_driver:
            type: service
            id: doctrine.cache.memcache
        result_cache_driver:
            type: service
            id: doctrine.cache.memcache

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]