imports:
  - { resource: config.yml }
  - { resource: service.sae.yml }

parameters:
    kernel:
        cache_dir: 'saemc://var/cache/%kernel.environment%'
        logs_dir: 'saemc://var/logs/$kernel.environment%'

framework:
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.memcache
    annotations:
        cache: doctrine.cache.memcache

doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.cache.memcache
        query_cache_driver:
            type: service
            id: doctrine.cache.memcache
        result_cache_driver:
            type: service
            id: doctrine.cache.memcache

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]