appname: agarage
version: 1

handle:

#URL重写
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "^(.*)[\.css|\.js|\.map]1$") goto "/site/web/%1%2"
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "^(.*)$") goto "/site/web/app.php/%1"