<?php

/**
 * Created by PhpStorm.
 * User: nicholas
 * Date: 16-2-21
 * Time: 上午4:10
 */
class SaeAppKernel extends AppKernel
{
    public function getCacheDir()
    {
        return 'saemc:///var/cache/'.$this->getEnvironment(); // TODO: Change the autogenerated stub
    }
}